services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    # If image is not building due to platform (on windows) you can uncomment this line
    # platform: linux/amd64  
    container_name: "terno-ai"
    image: terno-ai:latest
    command: bash -c ". /code/terno-ai/setup.sh && python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - env-sample.sh
