services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "terno-ai"
    image: terno-ai:latest
    command: bash -c ". ../setup.sh && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    networks:
      - app
    env_file:
      - env.sh

networks:
  app:
    external: true
    name: app