name: Code Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: python:3.10-slim

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Git and MySQL Dependencies
      run: |
        apt-get update
        apt-get install -y git
        apt install -y build-essential pkg-config libmariadb-dev
        apt install -y libpq-dev
   
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install psycopg2
        pip install mysqlclient
        pip install -r requirements.txt
   
    - name: Run Tests
      env:
        CSRF_TRUSTED_ORIGINS: ${{ secrets.CSRF_TRUSTED_ORIGINS }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: |
        coverage run terno/manage.py test terno && coverage report --fail-under=65 && coverage xml

    steps:
    - uses: actions/checkout@main
    - uses: codecov/codecov-action@v5
      with:
      fail_ci_if_error: true # optional (default = false)
      files: ./coverage1.xml,./coverage2.xml # optional
      flags: unittests # optional
      name: codecov-umbrella # optional
      token: ${{ secrets.CODECOV_TOKEN }}
      verbose: true # optional (default = false)